### PR TITLE
# 20 Phrase Extraction

### PR DESCRIPTION
**Pull request by JasonZhangzy1757**
Phrase Extraction using spaCy pipeline and library for transforming JSON to text divided by sections

### CODE REVIEW

**Comment by ceteri** [comment]
Hi @JasonZhangzy1757  this is getting closer to deliverable. Nice work. 

There are a few things still to check off the list:

1. I've made a commit with changes to the code: using codecs to handle UTF8, using pathlib.Path, glob, etc.  Can you please confirm that the code works as intended? Plus, those examples will be good patterns to use elsewhere in the code base.

2. Also: to test and validate, we must have some example JSON file from Parsr output to use as input for the `phrase_extraction_pipeline.py` step.  Please select one that's a good example of the Parsr output, and add that to `example/pub` in a commit.  

We'll develop unit tests from that, and even more immediately we both need to have some file in common to use so that we can replicate results.

**Comment by JasonZhangzy1757** [comment]
Hi @ceteri

I have downloaded the code and run on my computer, and it works perfectly. Also thanks for sharing the coding standard. I have noted them down and will bear them in mind. Hope next time I could get everything right. 

I've add an example in the commit. I think it's good, because it's not very long, and the headings are tagged where they should be. I think this might be good for designing a basic unit test. If this is not good enough, and you have any idea of what the examples should look like,  I'll find more of them if needed.

**Comment by ceteri** [comment]
Great, thanks @JasonZhangzy1757   That file helps a lot to debug!

I'm getting an exception -- have you seen anything like this before?
Perhaps some setting on my side is incorrect, but it seems to be in the "library" functions?

```
$ ./bin/phrase_extraction_pipeline.py
Traceback (most recent call last):
  File "./bin/phrase_extraction_pipeline.py", line 79, in <module>
    PhraseExtraction(resource_path)
  File "./bin/phrase_extraction_pipeline.py", line 39, in PhraseExtraction
    sections, titles = parsr_interpreter.GetSectionalText(object)
  File "/Users/paco/src/rclc/bin/parsed_json_interpreter.py", line 72, in GetSectionalText
    text_lists, titles = self.FindObject(object)
  File "/Users/paco/src/rclc/bin/parsed_json_interpreter.py", line 23, in FindObject
    for page in self.object['pages']:
TypeError: list indices must be integers or slices, not str
```

**Comment by JasonZhangzy1757** [comment]
It is strange, because I've test your code on scripts and notebook for several times, it all works well. Besides this seems an error in the library, but I've tried lots of files, still works well. I have never seen anything like this.

Based on the description of the error, it seems the error is raised because it thinks `self.object` is a list, and list indice can't be str, but I've looked into the type of `self.object` and it is a dictionary. So I'm a little confused why this happens. May I ask what json file you are using when the error is raised?

**Comment by ceteri** [comment]
No worries, and many thanks for your help!

There was a path problem on my side -- the `bin/phrase_extraction_pipeline.py` script is running now for me, and the results look really good.

I've changed the set up function, and added some parameters so we can switch between "test vs. prod" env, and turn off verbose output.

This is ready to merge -

**Review by ceteri — APPROVED** [review]
Looks great!

**Pull request merged**
